---
- name: Playbook that runs a Python script
  hosts: localhost

  vars:
          url: "http://api.open-notify.org/astros.json"

  tasks:
  - name: Lookup API with URI module
    uri:
            url: "{{ url }}"
            method: GET
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines

