---
- name: Copying files from controller to host
  hosts: planetexpress
  gather_facts: yes

  vars:
    mpresent: present
    mapps: [sl,figlet]

  tasks:

    - name: Apt update
      apt:
        update_cache: yes
      become: yes

    - name: Install apt packages
      apt:
        name: "{{ mapps }}" 
        state: "{{ mpresent }}"
      become: yes
