---
- name: Getting a file
  hosts: planetexpress
  gather_facts: no
  
  tasks:
  - name: "Download a file from HTTP"
    get_url: 
      url: https://raw.githubusercontent.com/mattincarlsbad/dell-ansible-training/master/README.md
      dest: ~/README.md
